export const foodItems = [
  {
    id: "food-1",
    title: "ዶሮ ወጥ",
    description: "ባህላዊ የኢትዮጵያ ዶሮ ወጥ በቤርቤሬ እና በተለያዩ ቅመሞች የተቀመመ",
    price: 350.0,
    category: "ዋና ምግቦች",
    type: "NON_VEG",
    spicyLevel: 3,
    preparationTime: 45,
    ingredients: ["ዶሮ", "ቤርቤሬ", "ሽንኩርት", "ነጭ ሽንኩርት", "ዘይት", "እንቁላል"],
    image: "/placeholder.svg?height=200&width=300",
    available: true,
  },
  {
    id: "food-2",
    title: "ክትፎ",
    description: "ጥሬ ስጋ በሚጣ እና በቅመሞች የተቀመመ",
    price: 280.0,
    category: "ዋና ምግቦች",
    type: "NON_VEG",
    spicyLevel: 4,
    preparationTime: 15,
    ingredients: ["ጥሬ ስጋ", "ሚጣ", "ቤርቤሬ", "ካርዳሞም"],
    image: "/placeholder.svg?height=200&width=300",
    available: true,
  },
  {
    id: "food-3",
    title: "ሽሮ ወጥ",
    description: "የተፈጨ አተር ወጥ በቅመሞች የተቀመመ",
    price: 120.0,
    category: "ዋና ምግቦች",
    type: "VEG",
    spicyLevel: 2,
    preparationTime: 30,
    ingredients: ["ሽሮ", "ሽንኩርት", "ነጭ ሽንኩርት", "ዘይት", "ቤርቤሬ"],
    image: "/placeholder.svg?height=200&width=300",
    available: true,
  },
  {
    id: "food-4",
    title: "ፍርፍር",
    description: "የተቀላቀሉ ወጦች በኢንጀራ ላይ",
    price: 200.0,
    category: "ዋና ምግቦች",
    type: "VEG",
    spicyLevel: 2,
    preparationTime: 25,
    ingredients: ["ሽሮ", "ምስር", "ጎመን", "ኢንጀራ"],
    image: "/placeholder.svg?height=200&width=300",
    available: true,
  },
  {
    id: "food-5",
    title: "ቡና",
    description: "ባህላዊ የኢትዮጵያ ቡና",
    price: 25.0,
    category: "መጠጦች",
    type: "VEG",
    spicyLevel: 0,
    preparationTime: 10,
    ingredients: ["የቡና ፍሬ", "ውሃ", "ስኳር"],
    image: "/placeholder.svg?height=200&width=300",
    available: true,
  },
  {
    id: "food-6",
    title: "ሻይ",
    description: "ሞቅ ያለ ሻይ በስኳር",
    price: 15.0,
    category: "መጠጦች",
    type: "VEG",
    spicyLevel: 0,
    preparationTime: 5,
    ingredients: ["ሻይ", "ውሃ", "ስኳር", "ወተት"],
    image: "/placeholder.svg?height=200&width=300",
    available: true,
  },
  {
    id: "food-7",
    title: "ቁርስ ኮምቦ",
    description: "እንቁላል፣ ዳቦ እና ሻይ",
    price: 85.0,
    category: "ቁርስ",
    type: "VEG",
    spicyLevel: 0,
    preparationTime: 15,
    ingredients: ["እንቁላል", "ዳቦ", "ሻይ", "ቅቤ"],
    image: "/placeholder.svg?height=200&width=300",
    available: true,
  },
  {
    id: "food-8",
    title: "ሾርባ",
    description: "ሞቅ ያለ የአትክልት ሾርባ",
    price: 65.0,
    category: "ሾርባዎች",
    type: "VEG",
    spicyLevel: 1,
    preparationTime: 20,
    ingredients: ["ካሮት", "ድንች", "ሽንኩርት", "ቲማቲም"],
    image: "/placeholder.svg?height=200&width=300",
    available: true,
  },
]

export const diningModes = [
  { id: "dine-in", name: "በሬስቶራንት ውስጥ", icon: "🍽️" },
  { id: "takeaway", name: "ይዘው ይሂዱ", icon: "🥡" },
  { id: "delivery", name: "ማድረስ", icon: "🚚" },
]

export const paymentTypes = [
  { id: "cash", name: "ጥሬ ገንዘብ", icon: "💵" },
  { id: "card", name: "ካርድ", icon: "💳" },
  { id: "mobile", name: "ሞባይል ክፍያ", icon: "📱" },
]
