import {
  Menu,
  TableIcon,
  CalendarRange,
  Truck,
  Calculator,
  Settings,
  Coffee,
  Soup,
  ChefHat,
  Sandwich,
  Grid,
} from "lucide-react"

// ዋና የምግብ ቤት መረጃ
export const restaurantInfo = {
  name: "ቺሊ POS",
  logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202025-01-12%20at%2012.32.42%20PM-QicgA83ZI0TfZlOynDOqlhOGnbwzEv.jpeg",
  primaryColor: "green", // ዋና ቀለም - green, blue, red, purple, orange, etc.
  secondaryColor: "orange", // ሁለተኛ ቀለም
}

// የጎን ማውጫ ምናሌዎች
export const navItems = [
  { icon: Menu, label: "ምናሌ", color: `text-${restaurantInfo.primaryColor}-600` },
  { icon: TableIcon, label: "የጠረጴዛ አገልግሎቶች", color: "text-gray-600" },
  { icon: CalendarRange, label: "ቦታ ማስያዝ", color: "text-gray-600" },
  { icon: Truck, label: "ማድረስ", color: "text-gray-600" },
  { icon: Calculator, label: "ሂሳብ", color: "text-gray-600" },
  { icon: Settings, label: "ቅንብሮች", color: "text-gray-600" },
]

// የምግብ ምድቦችን ለኢትዮጵያ ምግቦች ተስማሚ እናድርግ
export const foodCategories = [
  { icon: Grid, label: "ሁሉም", items: "45 ምግቦች", active: true },
  { icon: Coffee, label: "ቁርስ", items: "8 ምግቦች" },
  { icon: ChefHat, label: "ዋና ምግቦች", items: "15 ምግቦች" },
  { icon: Soup, label: "ሾርባዎች", items: "6 ምግቦች" },
  { icon: Coffee, label: "መጠጦች", items: "10 ምግቦች" },
  { icon: Sandwich, label: "ፈጣን ምግቦች", items: "6 ምግቦች" },
]

// የምግብ አይነቶችን እናሻሽል
export const foodTypes = {
  VEG: { label: "አትክልታዊ", color: "bg-green-500" },
  NON_VEG: { label: "ስጋ", color: "bg-red-500" },
  FISH: { label: "ዓሳ", color: "bg-blue-500" },
  DAIRY: { label: "የወተት ተዋጽኦ", color: "bg-yellow-500" },
  SPICY: { label: "ቅመም", color: "bg-orange-500" },
}

// የኢትዮጵያ ምግቦች ዝርዝር
export const foodItems = [
  // ዋና ምግቦች
  {
    id: "injera-doro",
    image: "/placeholder.svg?height=200&width=300",
    title: "እንጀራ በዶሮ ወጥ",
    description: "ባህላዊ የኢትዮጵያ ዶሮ ወጥ ከእንጀራ ጋር",
    price: 250.0,
    category: "ዋና ምግቦች",
    type: "NON_VEG",
    spicyLevel: 3,
    preparationTime: 25,
    ingredients: ["እንጀራ", "ዶሮ", "በርበሬ", "ሽንኩርት", "ነጭ ሽንኩርት"],
    allergens: ["ግሉተን"],
    available: true,
  },
  {
    id: "kitfo",
    image: "/placeholder.svg?height=200&width=300",
    title: "ክትፎ",
    description: "ጥሬ የበሬ ስጋ በቅመም የተቀመመ",
    price: 300.0,
    category: "ዋና ምግቦች",
    type: "NON_VEG",
    spicyLevel: 2,
    preparationTime: 15,
    ingredients: ["የበሬ ስጋ", "ሚትሚታ", "ቅቤ", "አያይብ"],
    allergens: ["ወተት"],
    available: true,
  },
  {
    id: "tibs",
    image: "/placeholder.svg?height=200&width=300",
    title: "ጥብስ",
    description: "የተጠበሰ የበሬ ስጋ ከአትክልት ጋር",
    price: 280.0,
    category: "ዋና ምግቦች",
    type: "NON_VEG",
    spicyLevel: 2,
    preparationTime: 20,
    ingredients: ["የበሬ ስጋ", "ሽንኩርት", "ቲማቲም", "በርበሬ"],
    allergens: [],
    available: true,
  },
  {
    id: "shiro",
    image: "/placeholder.svg?height=200&width=300",
    title: "ሽሮ",
    description: "የተፈጨ አተር ወጥ",
    price: 120.0,
    category: "ዋና ምግቦች",
    type: "VEG",
    spicyLevel: 2,
    preparationTime: 15,
    ingredients: ["የተፈጨ አተር", "ሽንኩርት", "በርበሬ", "ዘይት"],
    allergens: [],
    available: true,
  },
  {
    id: "gomen",
    image: "/placeholder.svg?height=200&width=300",
    title: "ጎመን",
    description: "የተበሰለ ጎመን ከስጋ ጋር",
    price: 150.0,
    category: "ዋና ምግቦች",
    type: "NON_VEG",
    spicyLevel: 1,
    preparationTime: 30,
    ingredients: ["ጎመን", "የበሬ ስጋ", "ሽንኩርት", "ነጭ ሽንኩርት"],
    allergens: [],
    available: true,
  },

  // ቁርስ ምግቦች
  {
    id: "ful",
    image: "/placeholder.svg?height=200&width=300",
    title: "ፉል",
    description: "የተበሰለ ባቄላ በቅመም",
    price: 80.0,
    category: "ቁርስ",
    type: "VEG",
    spicyLevel: 1,
    preparationTime: 10,
    ingredients: ["ባቄላ", "ቲማቲም", "ሽንኩርት", "በርበሬ"],
    allergens: [],
    available: true,
  },
  {
    id: "kinche",
    image: "/placeholder.svg?height=200&width=300",
    title: "ቂንጬ",
    description: "የተፈጨ ስንዴ በወተት",
    price: 60.0,
    category: "ቁርስ",
    type: "DAIRY",
    spicyLevel: 0,
    preparationTime: 15,
    ingredients: ["ስንዴ", "ወተት", "ቅቤ", "ስኳር"],
    allergens: ["ግሉተን", "ወተት"],
    available: true,
  },
  {
    id: "genfo",
    image: "/placeholder.svg?height=200&width=300",
    title: "ገንፎ",
    description: "የገብስ ገንፎ በቅቤ",
    price: 70.0,
    category: "ቁርስ",
    type: "DAIRY",
    spicyLevel: 0,
    preparationTime: 20,
    ingredients: ["ገብስ", "ቅቤ", "በርበሬ"],
    allergens: ["ግሉተን", "ወተት"],
    available: true,
  },

  // ሾርባዎች
  {
    id: "chicken-soup",
    image: "/placeholder.svg?height=200&width=300",
    title: "የዶሮ ሾርባ",
    description: "ሙቅ የዶሮ ሾርባ ከአትክልት ጋር",
    price: 100.0,
    category: "ሾርባዎች",
    type: "NON_VEG",
    spicyLevel: 1,
    preparationTime: 30,
    ingredients: ["ዶሮ", "ካሮት", "ሽንኩርት", "ሴሎሪ"],
    allergens: [],
    available: true,
  },
  {
    id: "lentil-soup",
    image: "/placeholder.svg?height=200&width=300",
    title: "የምስር ሾርባ",
    description: "ጤናማ የምስር ሾርባ",
    price: 80.0,
    category: "ሾርባዎች",
    type: "VEG",
    spicyLevel: 1,
    preparationTime: 25,
    ingredients: ["ምስር", "ሽንኩርት", "ቲማቲም", "ቅመማ ቅመም"],
    allergens: [],
    available: true,
  },

  // መጠጦች
  {
    id: "tej",
    image: "/placeholder.svg?height=200&width=300",
    title: "ጠጅ",
    description: "ባህላዊ የማር ወይን",
    price: 150.0,
    category: "መጠጦች",
    type: "VEG",
    spicyLevel: 0,
    preparationTime: 5,
    ingredients: ["ማር", "ውሃ", "ሆፕስ"],
    allergens: ["አልኮል"],
    available: true,
    alcoholic: true,
  },
  {
    id: "coffee",
    image: "/placeholder.svg?height=200&width=300",
    title: "ቡና",
    description: "ባህላዊ የኢትዮጵያ ቡና",
    price: 40.0,
    category: "መጠጦች",
    type: "VEG",
    spicyLevel: 0,
    preparationTime: 10,
    ingredients: ["የቡና ፍሬ", "ስኳር"],
    allergens: [],
    available: true,
  },
  {
    id: "fresh-juice",
    image: "/placeholder.svg?height=200&width=300",
    title: "ትኩስ ጭማቂ",
    description: "የተለያዩ ፍራፍሬዎች ጭማቂ",
    price: 60.0,
    category: "መጠጦች",
    type: "VEG",
    spicyLevel: 0,
    preparationTime: 5,
    ingredients: ["ፍራፍሬዎች", "ውሃ", "ስኳር"],
    allergens: [],
    available: true,
  },

  // ፈጣን ምግቦች
  {
    id: "sambusa",
    image: "/placeholder.svg?height=200&width=300",
    title: "ሳምቡሳ",
    description: "የተጠበሰ ሳምቡሳ በስጋ ወይም አትክልት",
    price: 25.0,
    category: "ፈጣን ምግቦች",
    type: "NON_VEG",
    spicyLevel: 2,
    preparationTime: 5,
    ingredients: ["ዱቄት", "ስጋ", "ሽንኩርት", "ቅመማ ቅመም"],
    allergens: ["ግሉተን"],
    available: true,
  },
  {
    id: "roasted-barley",
    image: "/placeholder.svg?height=200&width=300",
    title: "ቆሎ",
    description: "የተጠበሰ ገብስ",
    price: 30.0,
    category: "ፈጣን ምግቦች",
    type: "VEG",
    spicyLevel: 0,
    preparationTime: 2,
    ingredients: ["ገብስ", "ጨው"],
    allergens: ["ግሉተን"],
    available: true,
  },
]

// የክፍያ ዘዴዎች
export const paymentMethods = [
  { id: "cash", label: "ጥሬ ገንዘብ" },
  { id: "card", label: "ክሬዲት/ዴቢት ካርድ" },
  { id: "qr", label: "ኪውአር ኮድ" },
]

// ታክስ መጠን
export const taxRate = 0.05 // 5%
