const permissions = [
  "view_dashboard",
  "create_users",
  "edit_users",
  "delete_users",
  "view_users",
  "manage_roles",
  "view_roles",
  "create_products",
  "edit_products",
  "delete_products",
  "view_products",
  "create_orders",
  "edit_orders",
  "delete_orders",
  "view_orders",
  "manage_purchase_orders",
  "view_reports",
  "manage_suppliers",
  "approve_orders",
  "manage_workflows",
  "view_budget_controls",
  "manage_budget_controls",
  "create_po_templates",
  "use_po_templates",
];

const rolePermissions = {
  admin: [
    "view_dashboard",
    "create_users",
    "edit_users",
    "delete_users",
    "view_users",
    "manage_roles",
    "view_roles",
    "create_products",
    "edit_products",
    "delete_products",
    "view_products",
    "create_orders",
    "edit_orders",
    "delete_orders",
    "view_orders",
    "manage_purchase_orders",
    "view_reports",
    "manage_suppliers",
    "approve_orders",
    "manage_workflows",
    "view_budget_controls",
    "manage_budget_controls",
    "create_po_templates",
    "use_po_templates",
  ],
  manager: [
    "view_dashboard",
    "view_users",
    "view_roles",
    "view_products",
    "view_orders",
    "view_reports",
    "manage_suppliers",
    "approve_orders",
    "manage_workflows",
    "view_budget_controls",
    "create_po_templates",
    "use_po_templates",
  ],
  employee: [
    "view_dashboard",
    "view_products",
    "view_orders",
    "view_reports",
  ],
  customer: [
    "view_products",
    "view_orders",
  ],
  finance_manager: [
    "view_orders",
    "manage_purchase_orders",
    "approve_orders",
    "manage_workflows",
    "view_budget_controls",
    "manage_budget_controls",
    "view_reports",
    "manage_suppliers",
  ],
};

export { permissions, rolePermissions };
